name: eos31ve
dependencies:
  - python=3.8
  - pip=20.0
  - pip:
    - torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - numpy=1.18
    - pandas=1.1.3
    - rdkit=2020.03
    - tqdm=4.48.0
    - typing-extensions=3.7.4.2
    - typed-argument-parser==1.5.4
    - tensorboardX=2.1
    - scikit-learn=0.22
    - hyperopt=0.2.4
    - requests