name: eos31ve
channels:
  - conda-forge
dependencies:
  - ipython=7.16.1
  - efelix::fpsim2=0.2.6
  - hyperopt=0.2.4
  - matplotlib=3.3.0
  - networkx=2.4
  - numpy=1.18
  - pandas=1.1.3
  - pip=20.0
  - python>=3.7
  - pytorch=1.6.0
  - rdkit=2020.03
  - scikit-learn=0.22
  - tensorboardX=2.1
  - typing-extensions=3.7.4.2
  - requests
  - tqdm=4.48.0
  - pip:
    - keras-self-attention==0.41.0
    - tensorflow==2.2.0
    - typed-argument-parser==1.5.4
    - gunicorn==20.0.4
    - py-healthcheck==1.10.1

